#: import main mainGUI
#:import SlideTransition kivy.uix.screenmanager.SlideTransition

<defaultScreen>:
    FloatLayout:
        id: defaultScreenLayout
        size:(700,500)
        
        Button:
            text: 'Back to main'
            on_release: 
                root.manager.current = 'main'
                root.manager.transition = SlideTransition(direction='right')
            size_hint: (.1,.1)
            pos:(0,0)
        


